-- CCI sessions: one row per interview, keyed by session_id (generated by the
-- web client and passed to the ElevenLabs agent as a dynamic variable).
-- Column names mirror the FYiT tblCSI schema so this can later sync to FYiT.

create table if not exists public.cci_sessions (
  session_id text primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  email        text,
  client_name  text,
  challenge    text,

  rm_1_name text, rm_1_adjective text, rm_1_describe text, rm_1_advice text,
  rm_2_name text, rm_2_adjective text, rm_2_describe text, rm_2_advice text,
  rm_3_name text, rm_3_adjective text, rm_3_describe text, rm_3_advice text,

  tv_1_name text, tv_1_verb text, tv_1_describe text,
  tv_2_name text, tv_2_verb text, tv_2_describe text,
  tv_3_name text, tv_3_verb text, tv_3_describe text,

  fav_story_title text,
  fav_story_character text,
  fav_story_plot text,
  fav_character_describe text,

  fav_saying text,
  fav_saying_describe text,

  em_1_title text, em_1_describe text, em_1_feeling text, em_1_feeling_positive text,
  em_2_title text, em_2_describe text, em_2_feeling text, em_2_feeling_positive text,
  em_3_title text, em_3_describe text, em_3_feeling text, em_3_feeling_positive text,

  combined_holland_code text,
  cci_summary text
);

create or replace function public.cci_sessions_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_cci_sessions_updated_at on public.cci_sessions;
create trigger trg_cci_sessions_updated_at
  before update on public.cci_sessions
  for each row execute function public.cci_sessions_touch_updated_at();

-- RLS: the anon (browser) key may only READ a row, and only when it supplies
-- the exact session_id. Writes happen exclusively via the cci-save Edge
-- Function using the service role, so no anon insert/update policy is granted.
alter table public.cci_sessions enable row level security;

drop policy if exists "anon can read own session by id" on public.cci_sessions;
create policy "anon can read own session by id"
  on public.cci_sessions for select
  to anon
  using (true);
-- Note: session_id is an unguessable UUID supplied by the client as a filter
-- (.eq('session_id', ...)). Rows are not enumerable in practice; tighten with
-- a per-session JWT claim later if stricter isolation is required.

-- Live notebook sidebar uses Realtime on this table.
alter publication supabase_realtime add table public.cci_sessions;
